### ISSUE TITLE
More flexible typedef editing

### ISSUE THREAD

**Issue by georgefst** [hackworthltd/primer#1142]
We can now construct any type definition through the actions API. However, we still have several restrictions:
- [ ] We can only delete things from types if the type is not in use: #401.
- [ ] We can only modify the kinds of types if they are not in use: #402.
- [ ] We cannot re-order constructors, fields or parameters.
- [ ] We cannot attach name hints to student-defined types. The backend outputs them but we just don't have actions for them.

I intend to open fresh issues for those points above which do not currently have one.
