### ISSUE TITLE
Finishing the OpenAPI API

### ISSUE THREAD

**Issue by dhess** [hackworthltd/primer#605]
@brprice and I discussed today a strategy for finishing the OpenAPI API. At the time of writing, the OpenAPI API only supports the following:

* Creating a new session.
* Getting the list of sessions.
* Reading a given session's program, where the program type presented to OpenAPI clients is a simplified version of the core Primer program type, as we expect that TypeScript frontends will focus on rendering programs and handling user interactions while leaving the heavy lifting to the Haskell backend.

The remaining bits of the core API that we need in the OpenAPI API are:

* edits;
* questions; and
* evaluation.

(There are a few other minor API methods, but these are straightforward ports of the "legacy" API.)

I believe the original intention had been to move functionality from the legacy API, piece by piece and on a just-in-time basis, to the OpenAPI API, gradually replacing the former with the latter. However, we're now rethinking this strategy; see below.

[Note: from this point forward, I'll refer to the legacy API as the Servant API, since that's how it's implemented.]

The tentative plan is this:

* [x] I will switch the existing Servant API and the current OpenAPI API over to Servant's new `NamedRoutes` mechanism. (#612)
* [x] I will re-add to the Servant API the API endpoints that we previously moved (rather than copied) to the OpenAPI API, as we're no longer planning to remove the Servant API, and therefore it should probably cover the entire core API as it used to. As part of this work, I plan to rationalize the Servant API's session endpoints so that they resemble the OpenAPI API (e.g., use URL parameters rather than query parameters per #594). (#622)
* [x] I will port the remaining straightforward Servant API methods to the OpenAPI API, leaving "just" the edit, question, and eval APIs to port to OpenAPI. (#623)
* [x] At @brprice's suggestion, I will then take a pass at porting the `BodyAction` subset of the edit API to OpenAPI, as this should be a straightforward port without the need for (m)any simplified OpenAPI types.
* [ ] ~As @georgefst will be doing most of the upcoming tree/actions work in the frontend, he is probably best situated to port the remaining bits of the edit API, and the question API, over to OpenAPI.~ Only typedefs and modules remain.
* [x] As @brprice is currently working on an audit of the evaluation system, he's probably best situated to port the evaluation API to OpenAPI.

For background, @brprice and I discussed the following major points:

## OpenAPI types vs. core types

Based on my recent speculative OpenAPI work, where I attempted to move the whole Servant API to OpenAPI in one swoop, we may have underestimated the number of types that need to be simplified in OpenAPI, and there may be more work needed than we expected to create "dumb" frontend-friendly versions of the remaining Servant API endpoints, especially evaluation and (some) edits. For example, the Servant evaluation API takes as an argument an expression to evaluate, but a TypeScript frontend is not expected to know what an expression is, or at least, not to the same extent as a Haskell Servant client would.

Creating simplified OpenAPI types for each core type that we want to expose via these remaining API endpoints will be a maintenance burden, so alternatively we could either a) dumb down the core types so that they're identical to the OpenAPI types, or b) expose the full core types via OpenAPI. Neither I nor @brprice thinks either of these is a good idea, so we'll just need to bite the bullet and implement the simplified types as needed.

## Keep the Servant API, or just discard it

Arguably it would be more work in the long run to maintain both the Servant API and the OpenAPI API. We don't expect to write a full frontend client in Haskell (or PureScript) anytime soon, as our full focus is currently on our new TypeScript frontend.

However, we already have a Servant API, and especially once we've converted it (and the OpenAPI) to Servant's new `NamedRoutes` record-based mechanism, it should be relatively easy to maintain; it is, after all, just a thin layer on top of the `primer` core Haskell API.

Furthermore, while we don't expect to write a frontend client in Haskell in the near future, it would be very useful to be able to write Haskell programs that use the Servant API client bindings to interact with the Primer service over HTTP: for example, to add DSL-authored programs to the a live service's database, to do maintenance and cleanup, or to test the service over the wire.

Therefore, we agreed that we should keep the Servant API around, in addition to fleshing out the OpenAPI API.
